development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: zero_development

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: zero_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV["DATABASE_NAME"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
